language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
  - "4.2.0"
  - "5.1.0"

branches:
  only:
    - master

before_install:
  # Upgrade `npm` to avoid semver issues
  - if [[ $TRAVIS_NODE_VERSION == 0.10 ]]; then npm install -g npm@2.3.0; fi